# Generated by Django 4.2.4 on 2023-08-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_timestamp_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.account'),
        ),
    ]
