# Generated by Django 4.2.4 on 2023-08-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_budget_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
